python scripts/imitate_mj.py --mode gmmil \
  --seed 0 \
  --reward_type mmd \
  --env Walker2d-v1 \
  --data imitation_runs/modern_stochastic/trajs/trajs_walker.h5 \
  --limit_trajs 17 \
  --data_subsamp_freq 20 \
  --favor_zero_expert_reward 0 \
  --min_total_sa 50000 \
  --max_iter 1001 \
  --reward_include_time 0 \
  --log imitation_runs/modern_stochastic/checkpoints_all/alg=gmmil,task=walker,num_trajs=17,run=0.h5 \
